server:
  port: 10001
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: false
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl